name: Deploy Staging
# Staging URL: https://places-cpsc455-staging.herokuapp.com/

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Sleep for 12 minutes
        run: sleep 12m
        shell: bash
      - name: Deploy Staging
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_STAGING }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
